version: '3.8'
services:
  mongodb:
    image: mongo:5.0.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=nest-pokemon
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/data/db
